"""Train a custom wake word for Purple (default: "hey purple") with openWakeWord.

This orchestrates openWakeWord's OWN training pipeline (the maintained code), so the
actual training logic isn't reinvented here — this script just wires it together:

  1. clones openWakeWord + piper-sample-generator (synthetic-speech generator),
  2. installs the training dependencies,
  3. writes a training config for your phrase,
  4. runs openWakeWord's three phases: generate clips -> augment -> train,
  5. copies the resulting <name>.onnx into Purple's models/ folder.

Run on YOUR PC (a GPU makes it much faster). It is a one-time, somewhat heavy step
(downloads a few GB of background/augmentation data the first time).

    python scripts/train_wake.py --word "hey purple"

Then in .env:
    PURPLE_ENABLE_WAKE=true
    PURPLE_WAKE_MODEL=models/hey_purple.onnx

IF ANYTHING FAILS: openWakeWord's training API changes occasionally. The guaranteed
path is their official Colab notebook (see docs/wake_word.md) — it produces the same
hey_purple.onnx, which you just drop into models/. This script is the local convenience.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import shutil
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]  # project root
OWW_REPO = "https://github.com/dscripka/openWakeWord"
PIPER_REPO = "https://github.com/rhasspy/piper-sample-generator"


def run(cmd: list[str], cwd: Path | None = None) -> None:
    print(f"\n$ {' '.join(cmd)}", flush=True)
    subprocess.run(cmd, cwd=str(cwd) if cwd else None, check=True)


def main() -> int:
    ap = argparse.ArgumentParser(description="Train a custom openWakeWord wake word for Purple.")
    ap.add_argument("--word", default="hey purple", help='wake phrase, e.g. "hey purple"')
    ap.add_argument("--name", default="", help="model name (default: phrase slug, e.g. hey_purple)")
    ap.add_argument("--samples", type=int, default=2000, help="positive clips to generate (more = sturdier)")
    ap.add_argument("--workdir", default=str(ROOT / ".wake_training"), help="scratch dir for repos + data")
    ap.add_argument("--out", default=str(ROOT / "models"), help="where to copy the finished .onnx")
    args = ap.parse_args()

    name = args.name or args.word.strip().lower().replace(" ", "_")
    work = Path(args.workdir).resolve()
    out = Path(args.out).resolve()
    work.mkdir(parents=True, exist_ok=True)
    out.mkdir(parents=True, exist_ok=True)
    oww = work / "openWakeWord"
    piper = work / "piper-sample-generator"

    print(f"== Training wake word '{args.word}' -> {name}.onnx ==")
    print(f"   workdir: {work}\n   output : {out}\n")

    # 1. Get the tools.
    if not oww.exists():
        run(["git", "clone", "--depth", "1", OWW_REPO, str(oww)])
    if not piper.exists():
        run(["git", "clone", "--depth", "1", PIPER_REPO, str(piper)])

    # 2. Install training deps (best-effort; openWakeWord pulls torch etc. via its extra).
    run([sys.executable, "-m", "pip", "install", "--upgrade", "openwakeword[training]"])
    req = piper / "requirements.txt"
    if req.exists():
        run([sys.executable, "-m", "pip", "install", "-r", str(req)])

    # A piper voice is needed to synthesize the positive clips.
    voice = piper / "models" / "en_US-libritts_r-medium.pt"
    if not voice.exists():
        (piper / "models").mkdir(parents=True, exist_ok=True)
        run([
            sys.executable, "-c",
            "import urllib.request; urllib.request.urlretrieve("
            "'https://github.com/rhasspy/piper-sample-generator/releases/download/v2.0.0/"
            "en_US-libritts_r-medium.pt', r'%s')" % str(voice),
        ])

    # 3. Write a training config for openWakeWord's train.py.
    config = oww / "purple_training.yaml"
    config.write_text(
        f"""# Auto-generated by Purple scripts/train_wake.py
target_phrase: ["{args.word}"]
model_name: "{name}"
n_samples: {args.samples}
n_samples_val: {max(200, args.samples // 10)}
output_dir: "{(work / 'out').as_posix()}"
piper_sample_generator_path: "{piper.as_posix()}"
tts_batch_size: 50
augmentation_batch_size: 16
target_accuracy: 0.7
target_recall: 0.5
""",
        encoding="utf-8",
    )
    print(f"   wrote config: {config}")

    # 4. openWakeWord's documented 3-phase training.
    train_py = oww / "openwakeword" / "train.py"
    if not train_py.exists():
        train_py = oww / "train.py"
    for phase in ("--generate_clips", "--augment_clips", "--train_model"):
        run([sys.executable, str(train_py), "--training_config", str(config), phase], cwd=oww)

    # 5. Collect the result.
    produced = list((work / "out").rglob(f"{name}.onnx"))
    if not produced:
        print(
            "\n[!] Couldn't find the trained .onnx. openWakeWord's training layout may have\n"
            "    changed — use the official Colab notebook instead (docs/wake_word.md), then\n"
            f"    copy hey_purple.onnx into {out}. ",
            file=sys.stderr,
        )
        return 1
    dest = out / f"{name}.onnx"
    shutil.copy2(produced[0], dest)
    print(f"\n[ OK ] Trained model -> {dest}")
    print("Now set in .env:")
    print("    PURPLE_ENABLE_WAKE=true")
    print(f"    PURPLE_WAKE_MODEL=models/{name}.onnx")
    print('Restart Purple and say your wake word ("hey purple").')
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
